# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Uploader' do

pod 'Parse', '~> 1.13'
pod 'RealmSwift', '~> 0.99'
pod 'SWXMLHash', '~> 2.3.0'
pod 'Fingertips'
end
